version: "3.7"

services:

  app:
    build: ../gui
    restart: on-failure
    volumes:
      - lmt-data:/app
    environment:
      LMT_CONF_PATH: /app

  backend:
    image: asheswook/lightning-multitool:v0.1.6-beta
    init: true
    user: root
    restart: on-failure
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/root/.lnd:ro
      - lmt-data:/app
    entrypoint: >
      sh -c "/app/lmt 
      --configfile=/app/lmt.conf 
      --server.host=0.0.0.0 
      --server.port=5050 
      --lnd.host='${APP_LIGHTNING_NODE_HOST}:${APP_LIGHTNING_NODE_PORT}'"

volumes:
  lmt-data:
