version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: lightning-multitool_core_1
      APP_PORT: 5050

  app_ui_proxy:
    environment:
      APP_HOST: lightning-multitool_gui_1
      APP_PORT: 3000

  app-ui:
    build: ../gui
    restart: on-failure
    volumes:
      - lmt-data:/app
    environment:
      LMT_CONF_PATH: /app
      LMT_BACKEND_URL: http://backend:5050

  backend:
    image: asheswook/lightning-multitool:v0.1.6-beta
    init: true
    user: root
    restart: on-failure
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/root/.lnd:ro
      - lmt-data:/app
    entrypoint: >
      sh -c "/app/lmt 
      --configfile=/app/lmt.conf 
      --server.host=0.0.0.0 
      --server.port=5050 
      --lnd.host='${APP_LIGHTNING_NODE_HOST}:${APP_LIGHTNING_NODE_PORT}'"

volumes:
  lmt-data:
