version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: lightning-multitool_core_1
      APP_PORT: 3000

  gui:
    build: ../gui
    restart: on-failure
    volumes:
      - lmt-data:/app
    environment:
      LMT_CONF_PATH: /app
      LMT_BACKEND_URL: http://backend:5050

  backend:
    image: asheswook/lightning-multitool:v0.1.5-beta@sha256:d7304b09260b3f8925ccd5430efa7a8c58d61359c6b7f269c9e98e752e59357a
    user: "1000:1000"
    init: true
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/root/.lnd:ro
    command:
    entrypoint:
      - sh
      - -c
      - /app/lmt -general.username=test --server.host=${APP_HOST} --server.port=${APP_PORT} --lnd.host='${APP_LIGHTNING_NODE_HOST}:${APP_LIGHTNING_NODE_PORT}' --lnurl.domain=pororo.ro --server.host=0.0.0.0 --server.port=5001
      - /app/lmt --general.username=test --server.host=${APP_HOST} --server.port=${APP_PORT} --lnd.host='${APP_LIGHTNING_NODE_HOST}:${APP_LIGHTNING_NODE_PORT}' --lnurl.domain=pororo.ro --server.host=0.0.0.0 --server.port=5001

