version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ${APP_LMT_GUI_IP}
      APP_PORT: 3030

  gui:
    image: asheswook/lightning-multitool-umbrel:v0.0.7
    restart: on-failure
    volumes:
      - lmt-data:/app
    environment:
      LMT_CONF_PATH: /app
      LMT_CORE_URL: "http://${APP_LMT_IP}:${APP_LMT_API_PORT}"
    networks:
      default:
        ipv4_address: ${APP_LMT_GUI_IP}

  core:
    image: asheswook/lightning-multitool:v0.1.9-beta@sha256:80eacc378b5e976223725e08fdd784a46764a0a3dd1461ac2e78180cd260302f
    user: root
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    init: true
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/root/.lnd:ro
      - lmt-data:/app
    entrypoint:
      - sh
      - -c
      - /app/lmt
    ports:
      - ${APP_LMT_API_PORT}:${APP_LMT_API_PORT}
      - ${APP_LMT_PORT}:${APP_LMT_PORT}
    networks:
      default:
        ipv4_address: ${APP_LMT_IP}

volumes:
  lmt-data: