version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: lightning-multitool_app_1
      APP_PORT: 3030

  gui:
    image: asheswook/lightning-multitool-umbrel:v0.0.2
    restart: on-failure
    volumes:
      - lmt-data:/app
    environment:
      LMT_CONF_PATH: /app
      LMT_BACKEND_URL: http://backend:5050

  backend:
    image: asheswook/lightning-multitool:v0.1.5-beta@sha256:d7304b09260b3f8925ccd5430efa7a8c58d61359c6b7f269c9e98e752e59357a
    user: root
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    init: true
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/root/.lnd:ro
      - lmt-data:/app
    entrypoint:
      - sh
      - -c
      - /app/lmt

volumes:
  lmt-data: