version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ${APP_LMT_GUI_IP}
      APP_PORT: 3030

  gui:
    image: asheswook/lightning-multitool-umbrel:v0.0.9
    restart: on-failure
    volumes:
      - lmt-data:/app
    environment:
      LMT_CONF_PATH: /app
      LMT_CORE_URL: "http://${APP_LMT_IP}:${APP_LMT_API_PORT}"
    networks:
      default:
        ipv4_address: ${APP_LMT_GUI_IP}

  core:
    image: ghcr.io/asheswook/lightning-multitool:v0.1.12-beta@sha256:63f123fba1ca19a2e08cf2d1dab2a2be55203f06664519750e5d14ba96b9336c
    user: root
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    init: true
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/root/.lnd:ro
      - lmt-data:/app
    entrypoint:
      - sh
      - -c
      - /usr/local/bin/lmt
    environment:
      LND_HOST: ${APP_LIGHTNING_NODE_IP}:${APP_LIGHTNING_NODE_REST_PORT}
    ports:
      - ${APP_LMT_API_PORT}:${APP_LMT_API_PORT}
      - ${APP_LMT_PORT}:${APP_LMT_PORT}
    networks:
      default:
        ipv4_address: ${APP_LMT_IP}

volumes:
  lmt-data: